version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands: 
      - cd revfit
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'revfit/build'